project:
  type: website
  output-dir: docs

website:
  title: "Zuzanna Zagrodzka"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - publications.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

