---
title: "Publications"
# date: "2024-03-14"
date-modified: "2024-03-14"
about:
  # template: jolla
  # template: trestles
  # template: solana
  template: marquee
  # template: broadside
# format: 
#   html:
#     code-fold: true
---

Unfortunately, some of my work is not published Open Access. Feel free to contact me to request a copy of the article at z.zagrodzka\@sheffield.ac.uk.

\

\
[**Publications**]{.underline}

**Zagrodzka, Zuzanna B**., Thomas F. Johnson, and Andrew P. Beckerman. 2024. 'Accelerating the Open Research Agenda to Solve Global Challenges'. Ecology and Evolution 14 (2): e10887. <https://doi.org/10.1002/ece3.10887>.

Stankowski, Sean, **Zuzanna B. Zagrodzka**, Martin D. Garlovsky, Arka Pal, Daria Shipilina, Diego Garcia Castillo, Hila Lifchitz, et al. 2024. 'The Genetic Basis of a Recent Transition to Live-Bearing in Marine Snails'. Science 383 (6678): 114--19. <https://doi.org/10.1126/science.adi2982>.

Lenda, Magdalena, Bastian Steudel, Piotr Skórka, **Zuzanna B. Zagrodzka**, Dawid Moroń, Renata Bączek-Kwinta, Franciszek Janowiak, Agnieszka Baran, Hugh P. Possingham, and Johannes M. H. Knops. 2023. 'Multiple Invasive Species Affect Germination, Growth, and Photosynthesis of Native Weeds and Crops in Experiments'. Scientific Reports 13 (1): 22146. <https://doi.org/10.1038/s41598-023-48421-w>.

Stankowski, Sean, **Zuzanna B. Zagrodzka**, Martin D. Garlovsky, Arka Pal, Daria Shipilina, Diego Garcia Castillo, Alan Le Moan, et al. 2023. 'Selection on Many Loci Drove the Origin and Spread of a Key Innovation'. bioRxiv. <https://doi.org/10.1101/2023.02.13.528213>.

Raffini, Francesca, Aurélien De Jode, Kerstin Johannesson, Rui Faria, **Zuzanna B. Zagrodzka**, Anja M. Westram, Juan Galindo, Emilio Rolán-Alvarez, and Roger K. Butlin. 2023. 'Phenotypic Divergence and Genomic Architecture at Two Different Stages of Speciation in a Marine Snail'. bioRxiv. <https://doi.org/10.1101/2023.09.21.558824>.

Stankowski, Sean, **Zuzanna B Zagrodzka**, Juan Galindo, Mauricio Montaño-Rendón, Rui Faria, Natalia Mikhailova, April M H Blakeslee, et al. 2023. 'Whole-Genome Phylogeography of the Intertidal Snail Littorina Saxatilis'. Evolutionary Journal of the Linnean Society 2 (1): kzad002. <https://doi.org/10.1093/evolinnean/kzad002>.

Stankowski, Sean, Anja M. Westram, **Zuzanna B. Zagrodzka,** Isobel Eyres, Thomas Broquet, Kerstin Johannesson, and Roger K. Butlin. 2020. 'The Evolution of Strong Reproductive Isolation between Sympatric Intertidal Snails'. Philosophical Transactions of the Royal Society B: Biological Sciences 375 (1806): 20190545. <https://doi.org/10.1098/rstb.2019.0545>.

Johannesson, Kerstin, **Zuzanna Zagrodzka**, Rui Faria, Anja Marie Westram, and Roger K. Butlin. 2020. 'Is Embryo Abortion a Post‐zygotic Barrier to Gene Flow between Littorina Ecotypes?' Journal of Evolutionary Biology 33 (3): 342--51. <https://doi.org/10.1111/jeb.13570>.

Mattingsdal, Morten, Sissel Jentoft, Ole K. Tørresen, Halvor Knutsen, Michael M. Hansen, Joana I. Robalo, **Zuzanna Zagrodzka**, Carl André, and Enrique Blanco Gonzalez. 2018. 'A Continuous Genome Assembly of the Corkwing Wrasse (Symphodus Melops)'. Genomics 110 (6): 399--403. <https://doi.org/10.1016/j.ygeno.2018.04.009>.

Pansch, Christian, Giannina S. I. Hattich, Mara E. Heinrichs, Andreas Pansch, **Zuzanna Zagrodzka**, and Jonathan N. Havenhand. 2018. 'Long-Term Exposure to Acidification Disrupts Reproduction in a Marine Invertebrate'. PLOS ONE 13 (2): e0192036. <https://doi.org/10.1371/journal.pone.0192036>.

Ardehed, Angelica, Daniel Johansson, Lisa Sundqvist, Ellen Schagerström, **Zuzanna Zagrodzka**, Nikolaj A. Kovaltchouk, Lena Bergström, Lena Kautsky, Marina Rafajlovic, and Ricardo T. Pereyra. 2016. 'Divergence within and among Seaweed Siblings (Fucus Vesiculosus and F. Radicans) in the Baltic Sea'. PLoS One 11 (8): e0161266 <https://doi.org/10.1371/journal.pone.0161266>.
